export const DRAWER_TOGGLED = 'DRAWER_TOGGLED'

export const ACTIVITY_SEARCH_TEXT_UPDATED = 'ACTIVITY_SEARCH_TEXT_UPDATED'
export const SET_ACTIVITIES = 'SET_ACTIVITIES'
export const GET_CURRENT_ACTIVITY = 'GET_CURRENT_ACTIVITY'
