export const DRAWER_TOGGLED = 'DRAWER_TOGGLED'

export const ACTIVITY_SEARCH_TEXT_UPDATED = 'ACTIVITY_SEARCH_TEXT_UPDATED'
export const SET_ACTIVITIES = 'SET_ACTIVITIES'
export const GET_ACTIVITY = 'GET_CURRENT_ACTIVITY'

export const GET_CURRENT_BOAT = 'GET_CURRENT_BOAT'
export const SET_BOATS = 'SET_BOATS'
export const NEW_BOAT_SAVE_FAILED = 'NEW_BOAT_SAVE_FAILED'
export const NEW_BOAT_SAVED = 'NEW_BOAT_SAVED'
export const NEW_BOAT_SAVE_STARTED = 'NEW_BOAT_SAVE_STARTED'

export const SET_CREW = 'SET_CREW'
export const GET_CREW_MEMBER = 'GET_CREW_MEMBER'
export const NEW_CREW_SAVE_STARTED = 'NEW_CREW_SAVE_STARTED'
export const NEW_CREW_SAVE_SUCCEEDED = 'NEW_CREW_SAVE_SUCCEEDED'
export const NEW_CREW_SAVE_FAILED = 'NEW_CREW_SAVE_FAILED'
export const NEW_CREW_CLEARED = 'NEW_CREW_CLEARED'
export const NEW_CREW_FORM_UPDATED = 'NEW_CREW_FORM_UPDATED'
